### ISSUE TITLE
How to Build?

### ISSUE THREAD

**Issue by xDro1d** [blackberry/jwt-editor#7]
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:3.0.0:run (default) on project jwt-editor: An Ant BuildException has occured: Unable to find a javac compiler;
[ERROR] com.sun.tools.javac.Main is not on the classpath.
[ERROR] Perhaps JAVA_HOME does not point to the JDK.
[ERROR] It is currently set to "D:\Java_Home\jdk8u131\jre"
[ERROR] around Ant part ...<javac2 includeantruntime="false" destdir="C:\Users\pc\Desktop\jwt-editor\target/classes">... @ 8:95 in C:\Users\pc\Desktop\jwt-editor\target\antrun\build-main.xml

**Comment by DolphFlynn** [comment]
This error is due to you attempting to build with a JRE rather than a JDK. Try downloading a JDK (e.g. from https://jdk.java.net/) and configure JAVA_HOME to point to this. 

If you only want to use this code within Burp, then you can install it prebuilt via the BApp Store.

Hope that helps!
